version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd rules-service
      - mvn compile
      - mvn package
      - mvn -DskipTests clean package
      - echo " building docker image"
      - docker build -t pod2-account-registry:latest .
      - docker tag pod2-account-registry:latest 408832051344.dkr.ecr.us-east-2.amazonaws.com/pod2-account-registry:account
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 408832051344.dkr.ecr.us-east-2.amazonaws.com/pod2-account-registry:account
      - printf '[{"name":"account-container","imageUri":"%s"}]' 408832051344.dkr.ecr.us-east-2.amazonaws.com/pod2-account-registry:account>taskdefinition.json
artifacts:
   files:
   - account-service/taskdefinition.json